### ISSUE TITLE
Unable to Access Commands from the Rstudio Terminal

### ISSUE THREAD

**Issue by asimumba** [r-windows/rtools-installer#11]
Hi,

I am experiencing the following issue. I am unable to access commands such as `clear` and `ls` from inside the terminal using RStudio since installing Rtools40. 

System - Windows 10 and terminal set to use the Git bash.

This is the error output.

`   0 [main] cut (15576) C:\rtools40\usr\bin\cut.exe: *** fatal error - cygheap base mismatch detected - 0x180317408/0x180316408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
`
I seem to access the commands once I comment out this `PATH="${RTOOLS40_HOME}\usr\bin;${PATH}"` in the .Renviron file.

**Comment by jeroen** [comment]
This is a bug in rstudio: https://github.com/rstudio/rstudio/issues/6696

It is fixed in rstudio 1.3 which will be released later this month. You can get a preview here: https://rstudio.com/products/rstudio/download/preview/

As a workaround in the current rstudio you can type this line in the terminal tab:

```
PATH="/usr/bin:$PATH"
```

And after that things will work.

**Comment by asimumba** [comment]
Thank you. That worked. It is strange because I am on a preview version of RStudio.
